# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# API_KEY_ID = ENV["API_KEY_ID"]
# API_ISSUER_ID = ENV["API_ISSUER_ID"]
# API_PRIVATE_KEY = ENV["API_PRIVATE_KEY"]

KEYCHAIN_NAME = "keychain
KEYCHAIN_PASSWORD = "doinglab1011"

platform :ios do
  desc "Description of what the lane does"
  lane :app_build do

    create_keychain(
      name: KEYCHAIN_NAME,
      password: KEYCHAIN_PASSWORD,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_content: ENV["API_PRIVATE_KEY"]
    )

    sync_code_signing(
      type: "appstore",
#      app_identifier: "com.doinglab.NextDietCamera-GithubAction",
      readonly: true,
#      git_url: "https://github.com/hoBahk/FastlaneMatch.git",
      keychain_name: KEYCHAIN_NAME,
      keychain_password: KEYCHAIN_PASSWORD
    )


#    swiftlint(
#      mode: :lint,
#      raise_if_swiftlint_error: true,
#      ignore_exit_status: true
#    )

    gym(
      workspace: "GitHubActionsTest.xcworkspace",
      scheme: "GitHubActionsTest",
      clean: true,
      export_options: {
        manageAppVersionAndBuildNumber: true
      }
    )

  end


  lane :upload_testflight do

    app_build

    app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_content: ENV["API_PRIVATE_KEY"]
    )

    increment_build_number_in_xcodeproj # 빌드 넘버
#    increment_version_number_in_xcodeproj # 버전 넘버

    upload_to_testflight

#    version = get_version_number
#    noti_slack({"version": version })
  end


#  lane :noti_slack do |options| 
#    slack(
#      message: "앱이 testFlight에 성공적으로 업로드 되었습니다.",
#      channel: "#ios-team",
#      slack_url: [슬랙hook주소],
#      payload: {
#        "Version": options[:version]
#      }
#    )
#  end
end
