# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

API_KEY_ID = ENV["API_KEY_ID"]
API_ISSUER_ID = ENV["API_ISSUER_ID"]
API_PRIVATE_KEY = ENV["API_PRIVATE_KEY"]

platform :ios do
  desc "Description of what the lane does"
  lane :build do
#    get_certificates
#    get_provisioning_profile


     app_store_connect_api_key(
    		key_id: API_KEY_ID,
    		issuer_id: API_ISSUER_ID,
    		key_filepath: API_PRIVATE_KEY
    )

    gym(
	xcargs: "-allowProvisioningUpdates",
	project: "GitHubActionsTest.xcodeproj",
	scheme: "GitHubActionsTest"
	)

  error do |lane, exception, options|
    slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: "https://doinglabhq.slack.com/archives/D03DPKE950S",
    )
  end
    # add actions here: https://docs.fastlane.tools/actions
  end
end
