name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: macos-latest

    env:
      PROJECT: GitHubActionsTest.xcodeproj
      SCHEME: GitHubActionsTest
      CONFIGURATION: release
      DESTINATION: platform=iOS Simulator,name=iPhone 13,OS=latest

    steps:
    - uses: actions/checkout@v3

#    - uses: shimataro/ssh-key-action@v2
#      with:
#        key: ${{ secrets.SSH_KEY }}
#        known_hosts: ${{ secrets.KNOWN_HOSTS }}
#    - uses: actions/setup-node@v2
#      with:
#        node-version: ${{ matrix.node }}
#    - uses: actions/setup-ruby@v1
#      with:
#        ruby-version: ${{ matrix.ruby }}
    - run: brew install fastlane
    - run: pod install
    - run: fastlane build
    
    
#    - name: Selecct Xcode
#      run: sudo xcode-select -switch /Applications/Xcode.app
#    - name: Build
#      run: xcodebuild clean build test -allowProvisioningUpdates
#        -project "$PROJECT"
#        -scheme "$SCHEME"
#        -destination "$DESTINATION"

