name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    env:
      PROJECT: GitHubActionsTest.xcodeproj
      SCHEME: GitHubActionsTest
      CONFIGURATION: release
      DESTINATION: platform=iOS Simulator,name=iPhone 13,OS=latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Selecct Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - run: brew install fastlane
    - run: pod install

    - run: fastlane build
      env:
        FASTLANE_PASSWORD_FOR: ${{ secrets.FASTLANE_PASSWORD }}

