name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    env:
      PROJECT: GitHubActionsTest.xcodeproj
      SCHEME: GitHubActionsTest
      CONFIGURATION: release
      DESTINATION: platform=iOS Simulator,name=iPhone 13,OS=latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Selecct Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: install fastlane
      run: brew install fastlane
    
    - name: pod install
      run: pod install

    - name: app_build
      run: fastlane build
      env:
        FASTLANE_PASSWORD_FOR: ${{ secrets.FASTLANE_PASSWORD }}
        
#    - name: Upload TestFlight
#    - run: fastlane upload_testflight
#      env:
#        API_KEY_ID: ${{ secrets.API_KEY_ID }}
#        API_ISSUER_ID: ${{ secrets.API_ISSUER_ID }}
#        API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}
