name: Swift

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: macos-latest

    env:
      PROJECT: GitHubActionsTest.xcodeproj
      SCHEME: GitHubActionsTest
      CONFIGURATION: release
      DESTINATION: platform=iOS Simulator,name=iPhone 13,OS=latest
      MATCH_GIT_TOKEN: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
      MATCH_PW: ${{ secrets.MATCH_PW }}
      FASTLANE_PASSWORD_FOR: ${{ secrets.FASTLANE_PASSWORD }}

    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: bundle install

    - name: Selecct Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: install fastlane
      run: brew install fastlane

    - name: pod install
      run: pod install

    - name: app_build
      run: fastlane increment_build_number_do

    - name: Upload TestFlight
      run: fastlane upload_testflight
      env:
        API_KEY_ID: ${{ secrets.API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.API_ISSUER_ID }}
        API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}

#name: develop_branch
#
#on:
#  push:
#    branches: [ develop ]
#
#
#jobs:
#  build:
#    runs-on: macos-latest
#    env:
#      WORKSPACE: NextDietCamera.xcworkspace
#      PROJECT: DietDiaryAI.xcodeproj
#      SCHEME: DietDiaryAI
#      CONFIGURATION: release
#      DESTINATION: platform=iOS Simulator,name=iPhone 13,OS=latest
#
#      MATCH_GIT_AUTHORIZATION: ${{ secrets.MATCH_GIT_AUTHORIZATION }}
#      FASTLANE_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_SPECIFIC_PASSWORD }}
#      ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
#      TEAM_ID: ${{ secrets.TEAM_ID }}
#      MATCH_PW: ${{ secrets.MATCH_PW }}
#      FASTLANE_PW: ${{ secrets.FASTLANE_PW }}
#
#    steps:
#    # step 1
#    - name: Checkout Source Code
#      uses: actions/checkout@v3
#
#     step 2
#    - name: Install ruby & Bundle
#      uses: ruby/setup-ruby@v1
#      with:
#        ruby-version: 2.6
#    - run: bundle install
#
#    # step 3
#    - name: Select Xcode
#      run: sudo xcode-select -switch /Applications/Xcode.app
#
#    # step 4
#    - name: install fastlane
#      run: gem install fastlane
#
#    # step 5
#    - name: certify
#      run: fastlane certify
#
#    # step 6
#    - name: build
#      run: fastlane build
#      timeout-minutes: 40
#
#    # step 7
#    - name: UnitTest
#      run: fastlane unit_test
#
#    - name: action-slack
#      uses: 8398a7/action-slack@v3
#      with:
#        status: ${{ job.status }}
#        author_name: Github Action Test
#        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,
#        if_mention: failure,cancelled
#      env:
#        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#      if: always()
